git:
  depth: 1

matrix:
  include:
    - os: linux
      dist: xenial
      env: BUILD_MINGW=false
    - os: linux
      dist: xenial
      env: BUILD_MINGW=true
    - os: osx
      osx_image: xcode10.1
      nv: BUILD_MINGW=false

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq autoconf automake build-essential cmake git libass-dev libbz2-dev libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev libjansson-dev liblzma-dev libmp3lame-dev libogg-dev libopus-dev libsamplerate-dev libspeex-dev libtheora-dev libtool libtool-bin libvorbis-dev libx264-dev libxml2-dev m4 make patch pkg-config python tar yasm zlib1g-dev  ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$BUILD_MINGW" == false ]]; then sudo apt-get install -qq intltool libappindicator-dev libdbus-glib-1-dev libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libgudev-1.0-dev libnotify-dev libwebkitgtk-3.0-dev nasm  ; fi
- if [[ "$BUILD_MINGW" == true ]]; then sudo apt-get install -qq pax ; fi

language: c

script:

# Linux Build Support
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$BUILD_MINGW" == false  ]]; then ./configure --disable-gst --launch --launch-jobs=0 ; fi

# MinGW Build Support
- if [[ "$BUILD_MINGW" == true && -d "~/toolchains/mingw-w64-5.0.2-gcc-7.1.0" ]]; then ./scripts/mingw-w64-build x86_64 && ./scripts/mingw-w64-build x86_64.clean  ; fi
- if [[ "$BUILD_MINGW" == true ]]; then wget https://www.nasm.us/pub/nasm/releasebuilds/2.14/nasm-2.14.tar.gz ; fi
- if [[ "$BUILD_MINGW" == true ]]; then tar xvf nasm-2.14.tar.gz && cd nasm-2.14/ && ./configure && make && cd ..  ; fi
- if [[ "$BUILD_MINGW" == true ]]; then export PATH=/home/travis/build/HandBrake/HandBrake/nasm-2.14/:$HOME/toolchains/mingw-w64-5.0.2-gcc-7.1.0/mingw-w64-x86_64/bin:$PATH ; fi
- echo $PATH
- if [[ "$BUILD_MINGW" == true ]]; then ./configure --cross=x86_64-w64-mingw32 --enable-nvenc --enable-qsv --enable-vce --launch --launch-jobs=0 ; fi

# Macos Build Support
- if [[ "$TRAVIS_OS_NAME" == "osx" && -d "$HOME/toolchains/mac" ]]; then sudo ./scripts/mac-toolchain-build ~/toolchains/mac  ; fi
- if [[ "$BUILD_MINGW" == true ]]; then wget https://www.nasm.us/pub/nasm/releasebuilds/2.14/nasm-2.14.tar.gz ; fi
- if [[ "$BUILD_MINGW" == true ]]; then tar xvf nasm-2.14.tar.gz && cd nasm-2.14/ && ./configure && make && cd ..  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/home/travis/build/HandBrake/HandBrake/nasm-2.14/:$HOME/toolchains/mac/bin:$PATH ; fi
- echo $PATH
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure --launch --launch-jobs=0 ; fi


cache:
  directories:
  - $HOME/toolchains
