git:
  depth: 1

matrix:
  include:
    - os: linux
      dist: xenial
      env: BUILD_MINGW=false
    - os: linux
      dist: xenial
      env: BUILD_MINGW=true

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq autoconf automake build-essential cmake git libass-dev libbz2-dev libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev libjansson-dev liblzma-dev libmp3lame-dev libogg-dev libopus-dev libsamplerate-dev libspeex-dev libtheora-dev libtool libtool-bin libvorbis-dev libx264-dev libxml2-dev m4 make nasm patch pkg-config python tar yasm zlib1g-dev  ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq intltool libappindicator-dev libdbus-glib-1-dev libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libgudev-1.0-dev libnotify-dev libwebkitgtk-3.0-dev  ; fi

language: c

script:
- ls -la
- pwd

# Linux Build Support
- if [[ "$TRAVIS_OS_NAME" == "linux" ] && [ "$BUILD_MINGW" == false  ]]; then ./configure --disable-gtk --disable-gst --launch --launch-jobs=0 fi

# MinGW Build Support
- if [[  "$BUILD_MINGW" == true ] && [! -d "$HOME/toolchains" ]]; then ./scripts/mingw-w64-build x86_64 && ./scripts/mingw-w64-build x86_64.clean fi
- if [[  "$BUILD_MINGW" == true ]]; then export $HOME/toolchains/mingw-w64-5.0.2-gcc-7.1.0/mingw-w64-x86_64/bin;$PATH fi
- if [[  "$BUILD_MINGW" == true ]]; then echo $PATH fi

cache:
  directories:
  - $HOME/toolchains
